//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMCbizWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BlogMaster
    {
        public int BlogID { get; set; }
        public string BlogHeadLine { get; set; }
        public string ShortDescription { get; set; }
        public string Keywords { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
