//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMCbizWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMCUser
    {
        public int EnquieyId { get; set; }
        public string Name { get; set; }
        public string Emailid { get; set; }
        public string MobileNo { get; set; }

        public System.DateTime modifieddate { get; set; }
        public string modifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Createdate { get; set; }
        public bool Active { get; set; }
    }
}
